server:
  port: 9000


#spring:
#  application:
#    name: gateway-server # 应用名称
#  cloud:
#    gateway:
#      # 路由规则
#      routes:
#        - id: product-service           # 路由 ID，唯一
#          uri: http://localhost:9090/   # 目标 URI，路由到微服务的地址
#          predicates:                   # 断言（判断条件）
#            - Path=/product/**          # 匹配对应 URL 的请求，将匹配到的请求追加在目标 URI 之后
#        - id: order-service
#          uri: http://localhost:8080/
#          predicates:
#            - Path=/order/**

spring:
  application:
    name: gateway-server # 应用名称
  cloud:
    gateway:
      discovery:
        locator:
          # 是否与服务发现组件进行结合，通过serviceId转发到具体服务实例。
          enabled: true                  # 是否开启基于服务发现的路由规则
          lower-case-service-id: true    # 是否将服务名称转小写

# 配置Eureka Server注册中心
eureka:
  instance:
    prefer-ip-address: true       # 是否使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    service-url:                  # 设置服务注册中心地址
      defaultZone: http://localhost:8761/eureka/